name: Decrypt Secrets
run-name: Workflow for decrypting secrets
on: [ push ]

jobs:
  DecryptSecrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt secrets
        run: ./decrypt_secrets.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}