name: Decrypt Secrets
run-name: Workflow for decrypting secrets
on: [ push ]

jobs:
  DecryptSecrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt secrets
        run: ./decrypt_secrets.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat ./.env
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}